name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean install workaround for rollup native
        run: |
          rm -rf node_modules package-lock.json

      - name: Install deps
        run: npm install --force

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true # This ensures the process exits with a non-zero code if tests fail

      - name: Build
        run: npm run build
